name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build_no_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npx --no -- semantic-release --dry-run
